const responsiveStylesheet=document.createElement('link');responsiveStylesheet.rel='stylesheet';responsiveStylesheet.href='responsive.css';document.head.append(responsiveStylesheet);let state;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function whatsapp(message){const number=state?.settings?.whatsapp?.replace(/\D/g,'');return number?`https://wa.me/${number}?text=${encodeURIComponent(message)}`:'#contato'}
function dogCard(d){return `<article class="dog-card"><div class="dog-image"><img src="${d.image}" alt="Imagem demonstrativa: ${d.name}, Rottweiler" loading="lazy"></div><div class="dog-info"><div><h3>${d.name}</h3><p>Rottweiler · ${d.sex} · ${d.highlight}</p></div><span class="status">${d.status}</span></div><a class="text-link wa" data-message="Olá! Tenho interesse em saber mais sobre ${d.name}." href="#contato">Ver detalhes <b>→</b></a></article>`}
function puppyCard(d){return `<article class="puppy-card"><img src="${d.image}" alt="Imagem demonstrativa: ${d.name}" loading="lazy"><div><h3>${d.name}</h3><p>${d.sex} · ${d.status}</p><a class="text-link wa" data-message="Olá! Gostaria de saber mais sobre ${d.name}." href="#contato">Tenho interesse <b>→</b></a></div></article>`}
function bindLinks(){ $$('.wa').forEach(a=>a.onclick=e=>{const msg=a.dataset.message||'Olá! Gostaria de saber mais sobre o Canil Yannis do Oeste.';const link=whatsapp(msg);if(link==='#contato')return; e.preventDefault();open(link,'_blank','noopener');}); const insta=state.settings.instagram||'#';const desktopInstagram=$('#instagram'),mobileInstagram=$('#mobile-instagram');if(desktopInstagram)desktopInstagram.href=insta;if(mobileInstagram)mobileInstagram.href=insta; }
async function load(){state=await fetch('/api/data').then(r=>r.json());$('#dog-track').innerHTML=state.dogs.map(dogCard).join('');$('#puppy-grid').innerHTML=state.puppies.map(puppyCard).join('');document.title=`${state.settings.kennelName} | Rottweilers`; bindLinks();}
$('#year').textContent=new Date().getFullYear();$('.menu').onclick=()=>{const n=$('#nav'), open=n.classList.toggle('open');$('.menu').setAttribute('aria-expanded',open)};$('#prev').onclick=()=>$('#dog-track').scrollBy({left:-360,behavior:'smooth'});$('#next').onclick=()=>$('#dog-track').scrollBy({left:360,behavior:'smooth'});$('#dog-track').onkeydown=e=>{if(e.key==='ArrowRight')$('#next').click();if(e.key==='ArrowLeft')$('#prev').click()};
const admin=$('#admin');let adminToken='';$('.admin-link').onclick=e=>{e.preventDefault();adminToken=prompt('Informe a chave administrativa:')||'';if(!adminToken)return;$('#set-name').value=state.settings.kennelName||'';$('#set-wa').value=state.settings.whatsapp||'';$('#set-insta').value=state.settings.instagram||'';$('#json-editor').value=JSON.stringify(state,null,2);admin.showModal()};$('#save').onclick=async e=>{e.preventDefault();try{const next=JSON.parse($('#json-editor').value);next.settings.kennelName=$('#set-name').value.trim()||next.settings.kennelName;next.settings.whatsapp=$('#set-wa').value.trim();next.settings.instagram=$('#set-insta').value.trim();const r=await fetch('/api/data',{method:'PUT',headers:{'Content-Type':'application/json','X-Admin-Token':adminToken},body:JSON.stringify(next)});if(!r.ok)throw Error();$('#admin-status').textContent='Alterações salvas.';state=next;setTimeout(()=>{admin.close();load()},700)}catch{$('#admin-status').textContent='Não foi possível salvar. Revise o JSON e a chave.'}};
const light=$('#lightbox');$('#gallery-open').onclick=()=>{$('.gallery-grid img').click()};$$('.gallery-grid img').forEach(img=>img.onclick=()=>{light.querySelector('img').src=img.src;light.showModal()});
load().catch(()=>{ $('#dog-track').innerHTML='<p>Não foi possível carregar os cães.</p>'});
